In [1]:
import pandas as pd
import json

# 1. Baca file JSON
with open('gmaps_wisata_dekat_danau_toba_1745854280.json', 'r', encoding='utf-8') as file:
    data = json.load(file)

#gmaps_wisata_dekat_danau_toba_1745854280.json

In [2]:
# 2. Ubah ke DataFrame
df = pd.DataFrame(data)
df

,title,link,image_url,local_image_path,rating,reviews,address,opening_hours
0,Hill of Gibeon,https://www.google.com/maps/place/Hill+of+Gibe...,https://lh3.googleusercontent.com/gps-cs-s/AB5...,gmaps_images\Hill of Gibeon_1745853927.jpg,4.5,456.0,"Unnamed Road, Kabupaten Toba Samosir, 21174",Open 24 hours
1,Danau Toba Parapat,https://www.google.com/maps/place/Danau+Toba+P...,https://lh3.googleusercontent.com/gps-cs-s/AB5...,gmaps_images\Danau Toba Parapat_1745853928.jpg,4.7,510.0,,Open 24 hours
2,Bukit Burung,https://www.google.com/maps/place/Bukit+Burung...,https://lh3.googleusercontent.com/gps-cs-s/AB5...,gmaps_images\Bukit Burung_1745853929.jpg,4.8,140.0,,Open 24 hours
3,Pantai Bebas Parapat Danau Toba,https://www.google.com/maps/place/Pantai+Bebas...,https://lh3.googleusercontent.com/gps-cs-s/AB5...,gmaps_images\Pantai Bebas Parapat Danau Toba_1...,4.5,166.0,"MW9Q+G38 Danau Toba, Jl. Sisingamangaraja",Open now
4,Bukit Sibeabea,https://www.google.com/maps/place/Bukit+Sibeab...,https://lh3.googleusercontent.com/gps-cs-s/AB5...,gmaps_images\Bukit Sibeabea_1745853932.jpg,4.6,866.0,,NaN
...,...,...,...,...,...,...,...,...
115,Air Terjun Sipiso Piso,https://www.google.com/maps/place/Air+Terjun+S...,https://lh3.googleusercontent.com/gps-cs-s/AB5...,gmaps_images\Air Terjun Sipiso Piso_1745854262...,4.5,13.0,,Open 24 hours
116,Sopo Guru Tatea Bulan,https://www.google.com/maps/place/Sopo+Guru+Ta...,https://lh3.googleusercontent.com/gps-cs-s/AB5...,gmaps_images\Sopo Guru Tatea Bulan_1745854264.jpg,4.7,385.0,,Closed ⋅ Opens 12.00 am Tue
117,Tugu Marga Silalahi,https://www.google.com/maps/place/Tugu+Marga+S...,https://lh3.googleusercontent.com/gps-cs-s/AB5...,gmaps_images\Tugu Marga Silalahi_1745854267.jpg,4.5,886.0,,Open 24 hours
118,"PDA Panggung Drama Alam, BIS ANNEX",https://www.google.com/maps/place/PDA+Panggung...,https://lh3.googleusercontent.com/gps-cs-s/AB5...,"gmaps_images\PDA Panggung Drama Alam, BIS ANNE...",3.6,8.0,"RQ8J+5FW, Bukit Indah Simarjarunjung Annex PDA...",Open 24 hours
119,Sibea Bea,https://www.google.com/maps/place/Sibea+Bea/da...,https://lh3.googleusercontent.com/gps-cs-s/AB5...,gmaps_images\Sibea Bea_1745854270.jpg,4.6,12.0,HM2C+77,NaN

In [3]:

# 3. Simpan ke file Excel
df.to_excel('gmaps_wisata_dekat_danau_toba_1745853639.xlsx', index=False)

print("Data berhasil disimpan ke 'gmaps_wisata_dekat_danau_toba_1745853639.xlsx'")

Data berhasil disimpan ke 'gmaps_wisata_dekat_danau_toba_1745853639.xlsx'

In [4]:
# Fungsi untuk ekstrak koordinat dari link
def extract_coordinates(link):
    match = re.search(r'!3d(-?\d+\.\d+)!4d(-?\d+\.\d+)', link)
    if match:
        return float(match.group(1)), float(match.group(2))
    return None, None

# Tambahkan kolom latitude & longitude
df[['latitude', 'longitude']] = df['link'].apply(
    lambda x: pd.Series(extract_coordinates(x))
)

NameError: name 're' is not defined

In [5]:
import pandas as pd
import json
import re

# Baca file JSON
with open('gmaps_wisata_dekat_danau_toba_1745854280.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# Ubah ke DataFrame
df = pd.DataFrame(data)

# Fungsi untuk ekstrak koordinat dari link
def extract_coordinates(link):
    match = re.search(r'!3d(-?\d+\.\d+)!4d(-?\d+\.\d+)', link)
    if match:
        return float(match.group(1)), float(match.group(2))
    return None, None

# Tambahkan kolom latitude & longitude
df[['latitude', 'longitude']] = df['link'].apply(
    lambda x: pd.Series(extract_coordinates(x))
)

# Simpan ke Excel
df.to_excel('gmaps_danau_toba_with_coordinates.xlsx', index=False)

print("✅ Data disimpan ke 'gmaps_danau_toba_with_coordinates.xlsx' dengan koordinat.")

✅ Data disimpan ke 'gmaps_danau_toba_with_coordinates.xlsx' dengan koordinat.

In [8]:
import re

text = "AEK SIJORNIH PARIWISATA TOBA"
if re.search(r'AEK SIJORNIH', text, re.IGNORECASE):
    print("Ditemukan!")
else:
    print("Tidak ditemukan.")

Ditemukan!

In [9]:
# Filter baris yang title-nya mengandung "AEK SIJORNIH"
filtered_df = df[df['title'].str.contains(r'AEK SIJORNIH', flags=re.IGNORECASE, na=False)]

print(filtered_df)

Empty DataFrame
Columns: [title, link, image_url, local_image_path, rating, reviews, address, opening_hours, latitude, longitude]
Index: []

In [10]:
import re

text = "AEK SIJORNIH PARIWISATA TOBA"

if re.search(r'AEK SIJORNIH', text, re.IGNORECASE):
    print("Ditemukan!")
    print(f"Baris: {text}")
else:
    print("Tidak ditemukan.")

Ditemukan!
Baris: AEK SIJORNIH PARIWISATA TOBA

In [11]:
import pandas as pd
import json
import re

# Baca JSON ke DataFrame
with open('gmaps_wisata_dekat_danau_toba_1745854280.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

df = pd.DataFrame(data)

# Cari baris yang title-nya mengandung "AEK SIJORNIH"
filtered_df = df[df['title'].str.contains(r'AEK SIJORNIH', flags=re.IGNORECASE, na=False)]

# Tampilkan hasil
print(filtered_df)

Empty DataFrame
Columns: [title, link, image_url, local_image_path, rating, reviews, address, opening_hours]
Index: []

In [12]:
filtered_df = df[df['title'].str.contains(r'\bAEK\b', flags=re.IGNORECASE, na=False)]
print(filtered_df[['title', 'link']])

                       title  \
6                 Aek Rangat
24        Danau Aek Natonang
50  Pemandian Aek Sipitu Dai
67    Cottage Aek Tawar Sari

                                                 link
6   https://www.google.com/maps/place/Aek+Rangat/d...
24  https://www.google.com/maps/place/Danau+Aek+Na...
50  https://www.google.com/maps/place/Pemandian+Ae...
67  https://www.google.com/maps/place/Cottage+Aek+...

In [6]:
df

,title,link,image_url,local_image_path,rating,reviews,address,opening_hours,latitude,longitude
0,Hill of Gibeon,https://www.google.com/maps/place/Hill+of+Gibe...,https://lh3.googleusercontent.com/gps-cs-s/AB5...,gmaps_images\Hill of Gibeon_1745853927.jpg,4.5,456.0,"Unnamed Road, Kabupaten Toba Samosir, 21174",Open 24 hours,2.590828,98.997853
1,Danau Toba Parapat,https://www.google.com/maps/place/Danau+Toba+P...,https://lh3.googleusercontent.com/gps-cs-s/AB5...,gmaps_images\Danau Toba Parapat_1745853928.jpg,4.7,510.0,,Open 24 hours,2.683820,98.926076
2,Bukit Burung,https://www.google.com/maps/place/Bukit+Burung...,https://lh3.googleusercontent.com/gps-cs-s/AB5...,gmaps_images\Bukit Burung_1745853929.jpg,4.8,140.0,,Open 24 hours,2.631698,98.654911
3,Pantai Bebas Parapat Danau Toba,https://www.google.com/maps/place/Pantai+Bebas...,https://lh3.googleusercontent.com/gps-cs-s/AB5...,gmaps_images\Pantai Bebas Parapat Danau Toba_1...,4.5,166.0,"MW9Q+G38 Danau Toba, Jl. Sisingamangaraja",Open now,2.668398,98.937043
4,Bukit Sibeabea,https://www.google.com/maps/place/Bukit+Sibeab...,https://lh3.googleusercontent.com/gps-cs-s/AB5...,gmaps_images\Bukit Sibeabea_1745853932.jpg,4.6,866.0,,NaN,2.550670,98.673589
...,...,...,...,...,...,...,...,...,...,...
115,Air Terjun Sipiso Piso,https://www.google.com/maps/place/Air+Terjun+S...,https://lh3.googleusercontent.com/gps-cs-s/AB5...,gmaps_images\Air Terjun Sipiso Piso_1745854262...,4.5,13.0,,Open 24 hours,2.916487,98.519504
116,Sopo Guru Tatea Bulan,https://www.google.com/maps/place/Sopo+Guru+Ta...,https://lh3.googleusercontent.com/gps-cs-s/AB5...,gmaps_images\Sopo Guru Tatea Bulan_1745854264.jpg,4.7,385.0,,Closed ⋅ Opens 12.00 am Tue,2.591991,98.630636
117,Tugu Marga Silalahi,https://www.google.com/maps/place/Tugu+Marga+S...,https://lh3.googleusercontent.com/gps-cs-s/AB5...,gmaps_images\Tugu Marga Silalahi_1745854267.jpg,4.5,886.0,,Open 24 hours,2.812621,98.528421
118,"PDA Panggung Drama Alam, BIS ANNEX",https://www.google.com/maps/place/PDA+Panggung...,https://lh3.googleusercontent.com/gps-cs-s/AB5...,"gmaps_images\PDA Panggung Drama Alam, BIS ANNE...",3.6,8.0,"RQ8J+5FW, Bukit Indah Simarjarunjung Annex PDA...",Open 24 hours,2.815482,98.781202
119,Sibea Bea,https://www.google.com/maps/place/Sibea+Bea/da...,https://lh3.googleusercontent.com/gps-cs-s/AB5...,gmaps_images\Sibea Bea_1745854270.jpg,4.6,12.0,HM2C+77,NaN,2.550654,98.670661